name = "playbook-counter"
main = "src/index.js"
compatibility_date = "2025-01-01"

# Replace `id` after running `wrangler kv namespace create COUNTER`
[[kv_namespaces]]
binding = "COUNTER"
id = "9928d01eb57c4206b52adf31c337e376"
